# Generated by Django 2.2.3 on 2019-07-24 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0005_auto_20190724_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movableresource',
            name='availableEnd',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 25, 15, 30, 25, 664972, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movableresource',
            name='availableStart',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 15, 30, 25, 664972, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 15, 30, 25, 661979, tzinfo=utc)),
        ),
    ]
