# Generated by Django 2.2.3 on 2019-07-25 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0008_auto_20190724_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movableresource',
            name='availableEnd',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 26, 16, 21, 5, 730530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movableresource',
            name='availableStart',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 25, 16, 21, 5, 730530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 25, 16, 21, 5, 726511, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField()),
                ('isCorrect', models.BooleanField()),
                ('learning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='Education.Learning')),
            ],
        ),
    ]
