# Generated by Django 2.2.3 on 2019-07-25 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0009_auto_20190725_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='learning',
            name='name',
        ),
        migrations.AddField(
            model_name='learning',
            name='MaxAbility',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='learning',
            name='ability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learning',
            name='estimation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movableresource',
            name='availableEnd',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 26, 19, 46, 39, 28510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movableresource',
            name='availableStart',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 25, 19, 46, 39, 28510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 25, 19, 46, 39, 25516, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='learning',
            name='learningType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Education.LearningType'),
        ),
    ]
