# Generated by Django 2.2.3 on 2019-07-27 03:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0010_auto_20190725_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movableresource',
            name='availableEnd',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 3, 7, 25, 61348, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movableresource',
            name='availableStart',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 3, 7, 25, 61348, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 3, 7, 25, 57727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.FloatField(default=116.391467),
        ),
        migrations.AlterField(
            model_name='school',
            name='longitude',
            field=models.FloatField(default=39.927761),
        ),
    ]
