# Generated by Django 2.2.3 on 2019-07-27 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0011_auto_20190726_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movableresource',
            name='availableEnd',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 11, 50, 1, 429952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movableresource',
            name='availableStart',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 11, 50, 1, 429924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 11, 50, 1, 425378, tzinfo=utc)),
        ),
    ]
