# Generated by Django 2.2.3 on 2019-07-29 03:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0014_auto_20190728_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning',
            name='learningType',
        ),
        migrations.AddField(
            model_name='learning',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movableresource',
            name='availableEnd',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 3, 51, 48, 445632, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movableresource',
            name='availableStart',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 3, 51, 48, 445632, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 3, 51, 48, 440681, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='LearningType',
        ),
    ]
