# Generated by Django 2.2.3 on 2019-07-29 03:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0015_auto_20190728_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movableresource',
            name='availableEnd',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 3, 56, 44, 548011, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movableresource',
            name='availableStart',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 3, 56, 44, 548011, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 3, 56, 44, 544021, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='learning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='Education.Learning'),
        ),
    ]
