# Generated by Django 2.2.3 on 2019-07-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='SchoolLocation',
        ),
    ]
